#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : colcon-bash
Version  : 0.3.2
Release  : 4
URL      : https://files.pythonhosted.org/packages/68/87/8d2c2442fe5aec0af3aff168335ad38ed3546bbd247c1d33cd0c5375eebf/colcon-bash-0.3.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/68/87/8d2c2442fe5aec0af3aff168335ad38ed3546bbd247c1d33cd0c5375eebf/colcon-bash-0.3.2.tar.gz
Summary  : Extension for colcon to provide Bash scripts.
Group    : Development/Tools
License  : Apache-2.0
Requires: colcon-bash-python = %{version}-%{release}
Requires: colcon-bash-python3 = %{version}-%{release}
Requires: colcon-core
BuildRequires : buildreq-distutils3

%description
colcon-bash
===========
An extension for `colcon-core <https://github.com/colcon/colcon-core>`_ to provide `Bash <https://www.gnu.org/software/bash/>`_ scripts.

%package python
Summary: python components for the colcon-bash package.
Group: Default
Requires: colcon-bash-python3 = %{version}-%{release}

%description python
python components for the colcon-bash package.


%package python3
Summary: python3 components for the colcon-bash package.
Group: Default
Requires: python3-core

%description python3
python3 components for the colcon-bash package.


%prep
%setup -q -n colcon-bash-0.3.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1551476277
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
